name: Lint

on: push

jobs:
  build:
    # Name the Job
    name: Linter
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint YAML
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false # Being false it will analyse only the files that has been pushed not all the repo
          VALIDATE_YAML: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        #############################
        # Check go format           #
        #############################
      - name: Gofmt
        uses: Jerome1337/gofmt-action@v1.0.2
        with:
          gofmt-path: './src'
          gofmt-flags: '-l -d'
